import { Button, LineEdit, VerticalBox, CheckBox, GroupBox, TabWidget, HorizontalBox, StandardTableView } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 600px;
    min-height: 400px;
    title: "Blitz Backup";

    in-out property <string> backup-repository;
    in-out property <string> backup-password;

    callback save-settings();
    callback refresh-snapshots();

    TabWidget {
        Tab {
            title: "Backup";

            VerticalBox {
                alignment: start;

                GroupBox {
                    title: "General";

                    Button {
                        text: "Backup";
                    }
                }
            }
        }

        Tab {
            title: "Restore";

            VerticalBox {
                StandardTableView {
                    columns: [
                        { title: "ID" },
                        { title: "Time" },
                        { title: "Host" },
                        { title: "Tags" },
                        { title: "Paths" },
                    ];
                }

                HorizontalBox {
                    Button {
                        text: "Mount";
                    }

                    Button {
                        text: "Refresh";
                        clicked => {
                            root.refresh-snapshots()
                        }
                    }

                    Button {
                        text: "Restore";
                    }
                }
            }
        }

        Tab {
            title: "Settings";

            VerticalBox {
                alignment: start;
                padding: 5px;
                spacing: 5px;

                GroupBox {
                    title: "General";

                    GridLayout {
                        spacing: 5px;

                        Row {
                            Text {
                                text: "Repository: ";
                                vertical-alignment: center;
                            }

                            repository-textfield := LineEdit {
                                text: backup-repository;
                                placeholder-text: "Enter repository";
                            }
                        }

                        Row {
                            Text {
                                text: "Password: ";
                                vertical-alignment: center;
                            }

                            password-textfield := LineEdit {
                                text: backup-password;
                                placeholder-text: "Enter password";
                                input-type: password;
                            }
                        }
                    }
                }

                HorizontalLayout {
                    Rectangle {
                        preferred-width: 100%;
                    }

                    Button {
                        text: "Save";
                        clicked => {
                            root.backup-repository = repository-textfield.text;
                            root.backup-password = password-textfield.text;
                            root.save_settings()
                        }
                    }
                }
            }
        }
    }
}
