import { Button, LineEdit, VerticalBox, CheckBox, GroupBox, TabWidget, HorizontalBox, StandardTableView } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 600px;
    min-height: 400px;
    title: "Blitz Backup";

    in-out property <string> backup-repository;
    in-out property <string> backup-password;
    in-out property <string> backup-pathlist;

    callback save-settings();
    callback refresh-snapshots();
    callback init-repository();
    callback backup();
    callback mount();
    callback restore();
    callback forget();

    TabWidget {
        Tab {
            title: "Snapshots";

            VerticalBox {
                StandardTableView {
                    columns: [
                        { title: "ID" },
                        { title: "Time" },
                        { title: "Host" },
                        { title: "Tags" },
                        { title: "Paths" },
                    ];
                }

                GridLayout {
                    Row {
                        Button {
                            text: "Init";
                            clicked => {
                                root.init-repository();
                            }
                        }

                        Button {
                            text: "Backup";
                            clicked => {
                                root.backup();
                            }
                        }

                        Button {
                            text: "Refresh";
                            clicked => {
                                root.refresh-snapshots()
                            }
                        }
                    }

                    Row {
                        Button {
                            text: "Mount";
                            clicked => {
                                root.mount()
                            }
                        }

                        Button {
                            text: "Restore";
                            clicked => {
                                root.restore()
                            }
                        }

                        Button {
                            text: "Forget";
                            clicked => {
                                root.forget()
                            }
                        }
                    }
                }
            }
        }

        Tab {
            title: "Settings";

            VerticalBox {
                alignment: start;
                padding: 5px;
                spacing: 5px;

                GroupBox {
                    title: "General";

                    GridLayout {
                        spacing: 5px;

                        Row {
                            Text {
                                text: "Repository: ";
                                vertical-alignment: center;
                            }

                            repository-textfield := LineEdit {
                                text: backup-repository;
                                placeholder-text: "Enter repository";
                            }
                        }

                        Row {
                            Text {
                                text: "Password: ";
                                vertical-alignment: center;
                            }

                            password-textfield := LineEdit {
                                text: backup-password;
                                placeholder-text: "Enter password";
                                // input-type: password;
                            }
                        }

                        Row {
                            Text {
                                text: "Pathlist: ";
                                vertical-alignment: center;
                            }

                            pathlist-textfield := LineEdit {
                                text: backup-pathlist;
                                placeholder-text: "Enter pathlist";
                            }
                        }
                    }
                }

                HorizontalLayout {
                    Rectangle {
                        preferred-width: 100%;
                    }

                    Button {
                        text: "Save";
                        clicked => {
                            root.backup-repository = repository-textfield.text;
                            root.backup-password = password-textfield.text;
                            root.backup-pathlist = pathlist-textfield.text;
                            root.save_settings()
                        }
                    }
                }
            }
        }
    }
}
